### ISSUE TITLE
Porting to Inspect

### ISSUE THREAD

**Issue by mrahtz** [apartresearch/3cb#1]
Hi there! Thank you for accompanying your paper with such a thorough open-source release. The field of evals definitely needs more of this!

Is there any chance you'd have capacity to port 3CB to a shared framework for evals such as Inspect? https://inspect.ai-safety-institute.org.uk For folks running 3CB as part of a larger suite of evals it'd make onboarding 3CB much easier.

**Comment by esbenkc** [comment]
From discussions with AISI, METR, and others using Inspect, Inspect seems to become the de facto standard, so it's in our development roadmap. @derpyplops is currently on this task which [should be quite impactful](https://www.apartresearch.com/post/catastrophic-cyber-capabilities-benchmark-robustly-evaluating-llm-agent-cyber-offense-capabilities).

**Comment by mrahtz** [comment]
Excellent, thank you! I'll close this then.
